### ISSUE TITLE
Stop R307 from waiting to scan finger.

### ISSUE THREAD

**Issue by ShinNics** [bastianraschke/pyfingerprint#80]
Hi, 

what function can I use to make the fingerprint sensor stop from waiting an input.?

**Comment by raphaelreme** [comment]
Hi, 
I used this lib recently, with that device. There is no blocking function i believe.

If you want the fingerprint sensor to expect an input you can use the readImage method but this won't block (this will return quickly False if no finger has been detected).

In order to detect a finger you usually do:
```python
while not f.readImage():
   pass
```

But if you want to have more control, you can put a test inside your while loop

**Comment by bastianraschke** [comment]
You are right @raphaelreme, so i close the issue.
